blank_issues_enabled: false
contact_links:
  - name: 💡 Questions, ideas, discussions
    about: Ask a question or ask about a problem in GitHub Discussions.
    url: https://github.com/EmbeddedLLM/JAM.ai.dev/discussions
