services:
  infinity:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    extends:
      file: compose.cpu.yml
      service: infinity

  unstructuredio:
    extends:
      file: compose.cpu.yml
      service: unstructuredio

  docio:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    extends:
      file: compose.cpu.yml
      service: docio

  dragonfly:
    extends:
      file: compose.cpu.yml
      service: dragonfly

  owl:
    depends_on:
      infinity:
        condition: service_healthy
      unstructuredio:
        condition: service_healthy
      docio:
        condition: service_healthy
      dragonfly:
        condition: service_started
    extends:
      file: compose.cpu.yml
      service: owl

  frontend:
    extends:
      file: compose.cpu.yml
      service: frontend

networks:
  jamai:
