FROM python:3.12

RUN apt-get update \
    && apt-get install -y \
        ffmpeg \
        git \
        libavcodec-extra \
        poppler-utils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.5.8 /uv /uvx /bin/
