FROM node:20-alpine

ARG PUBLIC_JAMAI_URL=""
ARG PUBLIC_IS_SPA=false
ARG CHECK_ORIGIN=false
ENV PUBLIC_ADMIN_ORGANIZATION_ID="0"

WORKDIR /app
COPY ./services/app .
# RUN mv .env.example .env
RUN rm -rf .env
RUN npm ci

RUN PUBLIC_JAMAI_URL=${PUBLIC_JAMAI_URL} PUBLIC_IS_SPA=${PUBLIC_IS_SPA} CHECK_ORIGIN=${CHECK_ORIGIN} npx vite build
RUN mv temp build

RUN apk --no-cache add curl

CMD ["node", "server"]
