FROM docker.io/embeddedllminfo/jamaibase:ci

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --chown=$MAMBA_USER:$MAMBA_USER ./services/docio /app/services/docio
ARG MAMBA_DOCKERFILE_ACTIVATE=1  # (otherwise python will not be found)

RUN cd /app/services/docio && python -m pip install --no-cache-dir --upgrade .
